# Generated by Django 3.0.8 on 2021-01-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='total_savings',
        ),
    ]
