# Generated by Django 3.0.8 on 2021-01-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_total_savings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_postcode',
            new_name='default_zip_or_post',
        ),
    ]
