# Generated by Django 3.0.8 on 2021-01-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0002_auto_20210105_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='description_full',
            field=models.TextField(blank=True, null=True),
        ),
    ]
